name: Build Swift API
on: pull_request

jobs:
  test:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.2.app

      - name: Test on iOS
        run: set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-iOS -destination 'platform=iOS Simulator,name=iPhone 11 Pro' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test | xcpretty --color
        env:
          QMINDER_LOCATION_ID: ${{ secrets.QMINDER_LOCATION_ID }}
          QMINDER_API_KEY: ${{ secrets.QMINDER_API_KEY }}
          QMINDER_LINE_ID: ${{ secrets.QMINDER_LINE_ID }}
          QMINDER_USER_ID: ${{ secrets.QMINDER_USER_ID }}
          QMINDER_TV_ID: ${{ secrets.QMINDER_TV_ID }}

      - name: Codeconv
        run: |
          sed -i"any_symbol" "s/SLACK_KEY/${SLACK_KEY}/" codecov.yml
          bash <(curl -s https://codecov.io/bash)

      - name: SwiftPM Build
        run: swift build

      - name: Update ruby and cocoapods
        run: |
          sudo gem install cocoapods --no-doc
          sudo gem cleanup

      - name: Pod lib lint
        run: pod lib lint --allow-warnings

      - name: action-slack
        uses: 8398a7/action-slack@78391c20a77e510cde85f71fbd8175ce83f1ae6f # v2.7.0
        with:
          status: ${{ job.status }}
          author_name: GithubCI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build:
    name: Build on ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
          - watchOS
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.2.app

      - name: Build
        run: set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-${{ matrix.platform }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty --color

  compile-example-project:
    name: Compile example project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Example project
        run: |
          cd Example
          pod install
          xcodebuild clean build -workspace QminderTVApp.xcworkspace -scheme QminderTVApp CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
