name: Build Swift API
on: pull_request

jobs:
  test:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Test on iOS
        run: set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-iOS -destination 'platform=iOS Simulator,name=iPhone 15 Pro' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test | xcpretty --color
        env:
          QMINDER_LOCATION_ID: ${{ secrets.QMINDER_LOCATION_ID }}
          QMINDER_API_KEY: ${{ secrets.QMINDER_API_KEY }}
          QMINDER_LINE_ID: ${{ secrets.QMINDER_LINE_ID }}
          QMINDER_USER_ID: ${{ secrets.QMINDER_USER_ID }}
          QMINDER_TV_ID: ${{ secrets.QMINDER_TV_ID }}

      - name: Codeconv
        run: |
          sed -i"any_symbol" "s/SLACK_KEY/${SLACK_KEY}/" codecov.yml
          bash <(curl -s https://codecov.io/bash)

      - name: SwiftPM Build
        run: swift build

      - name: Update ruby and cocoapods
        run: |
          sudo gem install cocoapods --no-doc
          sudo gem cleanup

  build:
    name: Build on ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - macOS
          - watchOS
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Build
        run: set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-${{ matrix.platform }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty --color
