name: Build Swift API
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build and test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Start websockets test server
        run: |
          cd TestWebsockets
          brew install libressl
          brew install pkg-config
          swift build
          # .build/debug/TestWebsockets&
          # cd ..
          # set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES clean test build | xcpretty --color
