name: Release
on: workflow_dispatch

jobs:
  release:
    name: Release to CocoaPods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Update cocoapods
        run: |
          sudo gem install cocoapods --no-doc
          sudo gem cleanup

      - name: Release to CocoaPods register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
