name: Release
on: pull_request

jobs:
  release:
    name: Release to CocoaPods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Update cocoapods
        run: |
          sudo gem install cocoapods --no-doc
          sudo gem cleanup

      - name: Release to CocoaPods register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
